language: python
python:
  - "3.6"
install:
  - pip install -r requirements-dev.txt
script:
  - cp django_airavata/settings_local.py.sample django_airavata/settings_local.py
  - python manage.py migrate
  - python manage.py check
  # For now ignore long line endings
  - flake8 --ignore=E501 .
  - ./lint_js.sh
  - ./build_js.sh
  - ./test_js.sh
  # Need to build the frontend client before running some of the Django tests
  # that use the Django test Client
  - python manage.py test
